#.github/workflows/tests.yaml
name: Unit Tests

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    if: github.repository_owner == 'destination-earth-digital-twins'
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        env: [ "pytest" ]
        python-version: [ "3.10" ]

    name: "Unit-tests ${{ matrix.os }}, python=${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_READ_TOKEN }}

    container:
      image: python:${{ matrix.python-version }}-bullseye
      env:
        COVERAGE_FILE: ".coverage.${{ matrix.env }}.${{ matrix.python-version }}"

    steps:
      #----------------------------------------------
      #           check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      #----------------------------------------------
      #       setup github ssh token to authenticate for private repos in dependencies
      #----------------------------------------------
      - name: Set github credentials
        uses: ./.github/actions/setup-github-credentials
        with:
          github_token: ${{ env.GITHUB_TOKEN }}

      #----------------------------------------------
      #           add matrix specifics
      #----------------------------------------------
      - name: Install ping
        run: |
          apt-get update
          apt-get install -y inetutils-ping

      - name: Install system gdal libs
        run: |
          apt-get update
          apt-get install -y gdal-bin libgdal-dev

      - name: Install pygdal
        run: |
          pip install pygdal=="`gdal-config --version`.*"

      #----------------------------------------------
      #  --- configure poetry & install project  ----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv (if cache exists)
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ github.job }}-venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.toml') }}

      - name: Install dependencies (if venv cache is not found)
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --all-groups

      - name: Install the project itself
        run: poetry install --no-interaction --only-root

      #----------------------------------------------
      #      run test suite and report coverage
      #----------------------------------------------
      - name: Run tests
        run: |
          poetry run pytest -n auto


      # Disable upload to codecov until/if codecov is enabled
      # - name: Upload test coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./.coverage.xml
